### ISSUE TITLE
AttributeError: module 'jax' has no attribute 'custom_transforms'

### ISSUE THREAD

**Issue by fedetask** [deepmind/acme#112]
When trying to 
```python
from acme.jax import networks
```
I get the following error:

```
Traceback (most recent call last):
  File "jax_dqn.py", line 18, in <module>
    from acme.jax import networks
  File "/home/fedetask/Desktop/python-venv/lib/python3.7/site-packages/acme/jax/networks/__init__.py", line 29, in <module>
    from acme.jax.networks.distributional import CategoricalHead
  File "/home/fedetask/Desktop/python-venv/lib/python3.7/site-packages/acme/jax/networks/distributional.py", line 22, in <module>
    tfd = tensorflow_probability.experimental.substrates.jax.distributions
  File "/home/fedetask/Desktop/python-venv/lib/python3.7/site-packages/tensorflow_probability/python/internal/lazy_loader.py", line 57, in __getattr__
    module = self._load()
  File "/home/fedetask/Desktop/python-venv/lib/python3.7/site-packages/tensorflow_probability/python/internal/lazy_loader.py", line 44, in _load
    module = importlib.import_module(self.__name__)
  File "/home/fedetask/Desktop/python-venv/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/fedetask/Desktop/python-venv/lib/python3.7/site-packages/tensorflow_probability/substrates/jax/__init__.py", line 44, in <module>
    from tensorflow_probability.substrates.jax import bijectors
  File "/home/fedetask/Desktop/python-venv/lib/python3.7/site-packages/tensorflow_probability/substrates/jax/bijectors/__init__.py", line 23, in <module>
    from tensorflow_probability.substrates.jax.bijectors.absolute_value import AbsoluteValue
  File "/home/fedetask/Desktop/python-venv/lib/python3.7/site-packages/tensorflow_probability/substrates/jax/bijectors/absolute_value.py", line 23, in <module>
    from tensorflow_probability.substrates.jax.bijectors import bijector
  File "/home/fedetask/Desktop/python-venv/lib/python3.7/site-packages/tensorflow_probability/substrates/jax/bijectors/bijector.py", line 35, in <module>
    from tensorflow_probability.substrates.jax.math import gradient
  File "/home/fedetask/Desktop/python-venv/lib/python3.7/site-packages/tensorflow_probability/substrates/jax/math/__init__.py", line 23, in <module>
    from tensorflow_probability.substrates.jax.math import psd_kernels
  File "/home/fedetask/Desktop/python-venv/lib/python3.7/site-packages/tensorflow_probability/substrates/jax/math/psd_kernels/__init__.py", line 22, in <module>
    from tensorflow_probability.substrates.jax.math.psd_kernels.exp_sin_squared import ExpSinSquared
  File "/home/fedetask/Desktop/python-venv/lib/python3.7/site-packages/tensorflow_probability/substrates/jax/math/psd_kernels/exp_sin_squared.py", line 26, in <module>
    from tensorflow_probability.substrates.jax.math.psd_kernels.internal import util
  File "/home/fedetask/Desktop/python-venv/lib/python3.7/site-packages/tensorflow_probability/substrates/jax/math/psd_kernels/internal/util.py", line 110, in <module>
    def sqrt_with_finite_grads(x, name=None):
  File "/home/fedetask/Desktop/python-venv/lib/python3.7/site-packages/tensorflow_probability/python/internal/backend/jax/_utils.py", line 67, in wrap
    return new_fn(*args, **kwargs)
  File "/home/fedetask/Desktop/python-venv/lib/python3.7/site-packages/tensorflow_probability/python/internal/backend/jax/ops.py", line 422, in _custom_gradient
    @jax.custom_transforms
AttributeError: module 'jax' has no attribute 'custom_transforms'
```

My JAX versions are:
```commandline
jax                           0.2.12
jaxlib                        0.1.65+cuda112
```
My Tensorflow versions -that were installed by `pip install dm-acme[tf]` are:
```commandline
tensorflow                    2.4.1
tensorflow-probability        0.12.2
```

**Comment by fedetask** [comment]
It appears that a new release of JAX broke `tensorflow_probability`. [This issue](https://github.com/tensorflow/probability/issues/1289) explains how to temporarily fix the problem, but I hope a definitive solution will come soon.
