### ISSUE TITLE
Run out of GPU memory when running distributed agent 

### ISSUE THREAD

**Issue by Idate96** [deepmind/acme#121]
When running the example acme/examples/gym/lp_local_d4pg.py at the initialization stage I run out of GPU memory (1080 rtx) and the process fails. 

In the actor processes I get the following error 
```bash
I0522 20:03:38.349611 140210148575040 node.py:61] Reverb client connecting to: localhost:18200
Traceback (most recent call last):
  File "/home/lorenzo/acme/lib/python3.8/site-packages/launchpad/nodes/python/process_entry.py", line 80, in <module>
    app.run(main)
  File "/home/lorenzo/acme/lib/python3.8/site-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/home/lorenzo/acme/lib/python3.8/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/home/lorenzo/acme/lib/python3.8/site-packages/launchpad/nodes/python/process_entry.py", line 75, in main
    functions[task_id]()
  File "/home/lorenzo/acme/lib/python3.8/site-packages/launchpad/nodes/python/node.py", line 71, in _construct_function
    return functools.partial(self._function, *args, **kwargs)()
  File "/home/lorenzo/acme/lib/python3.8/site-packages/launchpad/nodes/courier/node.py", line 106, in run
    instance = self._construct_instance()  # pytype:disable=wrong-arg-types
  File "/home/lorenzo/acme/lib/python3.8/site-packages/launchpad/nodes/python/node.py", line 164, in _construct_instance
    return self._constructor(*args, **kwargs)
  File "/home/lorenzo/git/acme/acme/agents/tf/d4pg/agent_distributed.py", line 149, in actor
    networks = self._network_factory(self._environment_spec.actions)
  File "/home/lorenzo/git/acme/acme/agents/tf/d4pg/agent_distributed.py", line 67, in wrapped_network_factory
    networks_dict = network_factory(action_spec)
  File "/home/lorenzo/git/planning_2d/test_speed.py", line 118, in make_networks
    networks.DiscreteValuedHead(vmin, vmax, num_atoms),
  File "/home/lorenzo/acme/lib/python3.8/site-packages/sonnet/src/base.py", line 126, in __call__
    module.__init__(*args, **kwargs)
  File "/home/lorenzo/git/acme/acme/tf/networks/distributional.py", line 63, in __init__
    vmin = tf.convert_to_tensor(vmin)
  File "/home/lorenzo/acme/lib/python3.8/site-packages/tensorflow/python/util/dispatch.py", line 206, in wrapper
    return target(*args, **kwargs)
  File "/home/lorenzo/acme/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 1430, in convert_to_tensor_v2_with_dispatch
    return convert_to_tensor_v2(
  File "/home/lorenzo/acme/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 1436, in convert_to_tensor_v2
    return convert_to_tensor(
  File "/home/lorenzo/acme/lib/python3.8/site-packages/tensorflow/python/profiler/trace.py", line 163, in wrapped
    return func(*args, **kwargs)
  File "/home/lorenzo/acme/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 1566, in convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/home/lorenzo/acme/lib/python3.8/site-packages/tensorflow/python/framework/tensor_conversion_registry.py", line 52, in _default_conversion_function
    return constant_op.constant(value, dtype, name=name)
  File "/home/lorenzo/acme/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py", line 264, in constant
    return _constant_impl(value, dtype, shape, name, verify_shape=False,
  File "/home/lorenzo/acme/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py", line 276, in _constant_impl
    return _constant_eager_impl(ctx, value, dtype, shape, verify_shape)
  File "/home/lorenzo/acme/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py", line 301, in _constant_eager_impl
    t = convert_to_eager_tensor(value, ctx, dtype)
  File "/home/lorenzo/acme/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py", line 97, in convert_to_eager_tensor
    ctx.ensure_initialized()
  File "/home/lorenzo/acme/lib/python3.8/site-packages/tensorflow/python/eager/context.py", line 554, in ensure_initialized
    context_handle = pywrap_tfe.TFE_NewContext(opts)
tensorflow.python.framework.errors_impl.InternalError: CUDA runtime implicit initialization on GPU:0 failed. Status: out of memory
```

I tried on different hardware and I still get the same issue.
If I disable the GPU multiple actors are spawned successfully instead. Obviously it's much slower though. 

Any idea on how to fix it?

**Comment by fastturtle** [comment]
Hi @Idate96, by default TensorFlow processes allocate all of the GPUs memory. This is problematic when running multiple TF processes on the same machine (if they all have access to the same GPU). There are two ways to fix this issue:

1. Enable GPU memory growth in TF (see [TF docs](https://www.tensorflow.org/guide/gpu#limiting_gpu_memory_growth)). You have to make sure that this is done within each process Launchpad creates. If you use `tf.config.experimental.set_memory_growth` a good place to call it is from the `learner`, `actor`, and `evaluator` methods in [DistributedD4PG](https://github.com/deepmind/acme/blob/master/acme/agents/tf/d4pg/agent_distributed.py).
2. Prevent the actor and evaluator processes from using the GPU. An easy way to do this is to set the env var `CUDA_VISIBLE_DEVICES` to an empty string inside the processes Launchpad creates .

Here's an example for how to make sure Launchpad sets the env var correctly for subprocesses:

Inside [lp_local_d4pg.py](https://github.com/deepmind/acme/blob/master/examples/gym/lp_local_d4pg.py):

```
...
resources = {
    # The 'actor' and 'evaluator' keys refer to
    # the Launchpad resource groups created by Program.group()
    'actor':
        lp.PythonProcess(  # Dataclass used to specify env vars and args (flags) passed to the Python process
            env=dict(CUDA_VISIBLE_DEVICES='')),
    'evaluator':
        lp.PythonProcess(env=dict(CUDA_VISIBLE_DEVICES=''))
}
...
lp.launch(
    program, lp.LaunchType.LOCAL_MULTI_PROCESSING, local_resources=resources)

```

**Comment by Idate96** [comment]
Thanks a lot for the quick reply, indeed the problem stems from the memory growth in TF. 
For pp looking at the issue in the future remember to 
```python
from launchpad.nodes.python.local_multi_processing import PythonProcess
```
as PythonProcess is not the callable from lp.PythonProcess.

**Comment by vaxenburg** [comment]
Thank you @fastturtle !

When I try the first solution:

> 1. Enable GPU memory growth in TF (see TF docs). You have to make sure that this is done within each process Launchpad creates. If you use tf.config.experimental.set_memory_growth a good place to call it is from the learner, actor, and evaluator methods in DistributedD4PG.

I run into this error:

`[actor/0] RuntimeError: Physical devices cannot be modified after being initialized`

What I did was:

1. Made the GPU visible only to a single `actor` process (by setting the corresponding `CUDA_VISIBLE_DEVICES` variables).
2. Called `tf.config.experimental.set_memory_growth` from inside the `actor` method inside `DistributedD4PG` to control memory growth.

Does anyone else have this issue? Or am I missing something?
