### ISSUE TITLE
Distributed D4PG agent test

### ISSUE THREAD

**Issue by vaxenburg** [deepmind/acme#122]
I'm trying to run this "test", which is almost the same as the actual test for the D4PG distributed agent in https://github.com/deepmind/acme/blob/master/acme/agents/tf/d4pg/agent_distributed_test.py

I'm using the same `make_networks` function and the same call to instantiate the agent `agent = d4pg.DistributedD4PG(...)`. 

I believe the main difference (in addition to not being framed as a proper unit test) is that I'm running it in the `launch_type='local_mp'` mode, as I would in the actual agent training.

Here is the exact code I'm using:

```python
import acme
from acme import specs
from acme.agents.tf import d4pg
from acme.testing import fakes
from acme.tf import networks
from acme.tf import utils as tf2_utils
import launchpad as lp
import numpy as np
import sonnet as snt

def make_networks(action_spec: specs.BoundedArray):
  """Simple networks for testing.."""

  num_dimensions = np.prod(action_spec.shape, dtype=int)

  policy_network = snt.Sequential([
      networks.LayerNormMLP([50], activate_final=True),
      networks.NearZeroInitializedLinear(num_dimensions),
      networks.TanhToSpec(action_spec)
  ])
  # The multiplexer concatenates the (maybe transformed) observations/actions.
  critic_network = snt.Sequential([
      networks.CriticMultiplexer(
          critic_network=networks.LayerNormMLP(
              [50], activate_final=True)),
      networks.DiscreteValuedHead(-1., 1., 10)
  ])

  return {'policy': policy_network,
          'critic': critic_network,
          'observation': tf2_utils.batch_concat,}

agent = d4pg.DistributedD4PG(
    environment_factory=lambda x: fakes.ContinuousEnvironment(bounded=True),
    network_factory=make_networks,
    num_actors=2,
    batch_size=32,
    min_replay_size=32,
    max_replay_size=1000,
)
program = agent.build()
lp.launch(program, launch_type='local_mp', terminal='current_terminal')
```
Here is the traceback. Looks like something goes wrong with serialization? Or am I missing something? In case it's my bad I apologize in advance :)

```
Traceback (most recent call last):
  File "agent_distributed_test.py", line 48, in <module>
    lp.launch(program, launch_type='local_mp', terminal='current_terminal')
  File "/miniconda3/envs/acme/lib/python3.7/site-packages/launchpad/launch/launch.py", line 86, in launch
    terminal)
  File "/miniconda3/envs/acme/lib/python3.7/site-packages/launchpad/launch/local_multi_processing/launch.py", line 59, in launch
    nodes[0]._launch_context))
  File "/miniconda3/envs/acme/lib/python3.7/site-packages/launchpad/nodes/reverb/node.py", line 97, in to_executables
    return python.PyNode.to_executables(nodes, label, launch_context)
  File "/miniconda3/envs/acme/lib/python3.7/site-packages/launchpad/nodes/python/node.py", line 93, in to_executables
    nodes, label, launch_context.launch_config, pdb_post_mortem=True)
  File "/miniconda3/envs/acme/lib/python3.7/site-packages/launchpad/nodes/python/local_multi_processing.py", line 96, in to_multiprocessing_executables
    cloudpickle.dump([node.function for node in nodes], f)
  File "/miniconda3/envs/acme/lib/python3.7/site-packages/cloudpickle/cloudpickle_fast.py", line 88, in dump
    CloudPickler(file, protocol=protocol).dump(obj)
  File "/miniconda3/envs/acme/lib/python3.7/site-packages/cloudpickle/cloudpickle_fast.py", line 563, in dump
    return Pickler.dump(self, obj)
  File "/miniconda3/envs/acme/lib/python3.7/pickle.py", line 437, in dump
    self.save(obj)
  File "/miniconda3/envs/acme/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/miniconda3/envs/acme/lib/python3.7/pickle.py", line 816, in save_list
    self._batch_appends(obj)
  File "/miniconda3/envs/acme/lib/python3.7/pickle.py", line 843, in _batch_appends
    save(tmp[0])
  File "/miniconda3/envs/acme/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/miniconda3/envs/acme/lib/python3.7/site-packages/dill/_dill.py", line 1127, in save_instancemethod0
    pickler.save_reduce(MethodType, (obj.__func__, obj.__self__), obj=obj)
  File "/miniconda3/envs/acme/lib/python3.7/pickle.py", line 638, in save_reduce
    save(args)
  File "/miniconda3/envs/acme/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/miniconda3/envs/acme/lib/python3.7/pickle.py", line 771, in save_tuple
    save(element)
  File "/miniconda3/envs/acme/lib/python3.7/pickle.py", line 549, in save
    self.save_reduce(obj=obj, *rv)
  File "/miniconda3/envs/acme/lib/python3.7/pickle.py", line 662, in save_reduce
    save(state)
  File "/miniconda3/envs/acme/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/miniconda3/envs/acme/lib/python3.7/site-packages/dill/_dill.py", line 941, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "/miniconda3/envs/acme/lib/python3.7/pickle.py", line 856, in save_dict
    self._batch_setitems(obj.items())
  File "/miniconda3/envs/acme/lib/python3.7/pickle.py", line 882, in _batch_setitems
    save(v)
  File "/miniconda3/envs/acme/lib/python3.7/pickle.py", line 549, in save
    self.save_reduce(obj=obj, *rv)
  File "/miniconda3/envs/acme/lib/python3.7/pickle.py", line 662, in save_reduce
    save(state)
  File "/miniconda3/envs/acme/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/miniconda3/envs/acme/lib/python3.7/site-packages/dill/_dill.py", line 941, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "/miniconda3/envs/acme/lib/python3.7/pickle.py", line 856, in save_dict
    self._batch_setitems(obj.items())
  File "/miniconda3/envs/acme/lib/python3.7/pickle.py", line 882, in _batch_setitems
    save(v)
  File "/miniconda3/envs/acme/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/miniconda3/envs/acme/lib/python3.7/site-packages/cloudpickle/cloudpickle_fast.py", line 745, in save_function
    *self._dynamic_function_reduce(obj), obj=obj
  File "/miniconda3/envs/acme/lib/python3.7/site-packages/cloudpickle/cloudpickle_fast.py", line 682, in _save_reduce_pickle5
    dictitems=dictitems, obj=obj
  File "/miniconda3/envs/acme/lib/python3.7/pickle.py", line 638, in save_reduce
    save(args)
  File "/miniconda3/envs/acme/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/miniconda3/envs/acme/lib/python3.7/pickle.py", line 786, in save_tuple
    save(element)
  File "/miniconda3/envs/acme/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/miniconda3/envs/acme/lib/python3.7/pickle.py", line 771, in save_tuple
    save(element)
  File "/miniconda3/envs/acme/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/miniconda3/envs/acme/lib/python3.7/site-packages/dill/_dill.py", line 1177, in save_cell
    f = obj.cell_contents
ValueError: Cell is empty

```

**Comment by vaxenburg** [comment]
I realized that the code above works if I change the order of imports. Namely, it works if I move the line `import launchpad as lp` to the very top. Isn't it strange?

**Comment by qstanczyk** [comment]
Hi Roman, this is indeed an issue related to importing order.
Launchpad uses cloudpickle, while TF probabilities import dill. They don't colaborate perfectly - similar issues:
- https://github.com/uber/petastorm/issues/675
- https://stackoverflow.com/questions/66130711/pycaret-valueerror-cell-is-empty
We will look into addressing this problem one way or the other.

**Comment by vaxenburg** [comment]
Thanks so much @qstanczyk, this is very helpful!
