### ISSUE TITLE
Launchpad D4PG Agent Termination Not Working

### ISSUE THREAD

**Issue by Abinavraj5427** [deepmind/acme#137]
This issue is building off of this issue: #118 

Hello, I am currently trying to run the distributed D4PG program using launchpad. As mentioned earlier my coordinator is terminating, but my actors, learners, and evaluators are not terminating at `max_actor_steps`. 

I tried running this both with `dm-nighlty-launchpad==0.3.0.dev20210527` (as suggested in #118) and `dm-nightly-launchpad==0.3.0.dev20210621` with the setup in `requirements.txt`, and the same issue arose.

Testing code to replicate: [Example Code](https://github.com/Abinavraj5427/robosuiteRL-tests/blob/main/acme/d4pgdistro.py)

I haven't really used Acme before. Any ideas on what I can try?

**Comment by qstanczyk** [comment]
What does the main console (from which launcher is executed) prints out?

**Comment by Abinavraj5427** [comment]
My main console where I run my python file from prints out the following:
```
python3 d4pgdistro.py
2021-07-14 11:18:27.648515: E tensorflow/core/lib/monitoring/collection_registry.cc:77] Cannot register 2 metrics with the same name: /tensorflow/core/saved_model/write/count
2021-07-14 11:18:27.648567: E tensorflow/core/lib/monitoring/collection_registry.cc:77] Cannot register 2 metrics with the same name: /tensorflow/core/saved_model/read/count
2021-07-14 11:18:27.648587: E tensorflow/core/lib/monitoring/collection_registry.cc:77] Cannot register 2 metrics with the same name: /tensorflow/core/saved_model/write/api
2021-07-14 11:18:27.648601: E tensorflow/core/lib/monitoring/collection_registry.cc:77] Cannot register 2 metrics with the same name: /tensorflow/core/saved_model/read/api
/home/abinavraj10/.pyenv/versions/acme/lib/python3.8/site-packages/gym/logger.py:30: UserWarning: WARN: Box bound precision lowered by casting to float32
  warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))
b"Failed to register: Unable to acquire bus name 'launchpad.locallaunch.cacbahbebbbjbg'\n"
b"Failed to register: Unable to acquire bus name 'launchpad.locallaunch.cacbahbebbbjbg'\n"
b"Failed to register: Unable to acquire bus name 'launchpad.locallaunch.cacbahbebbbjbg'\n"
b"Failed to register: Unable to acquire bus name 'launchpad.locallaunch.cacbahbebbbjbg'\n"
b"Failed to register: Unable to acquire bus name 'launchpad.locallaunch.cacbahbebbbjbg'\n"
b"Failed to register: Unable to acquire bus name 'launchpad.locallaunch.cacbahbebbbjbg'\n"
b"Failed to register: Unable to acquire bus name 'launchpad.locallaunch.cacbahbebbbjbg'\n"
b"Failed to register: Unable to acquire bus name 'launchpad.locallaunch.cacbahbebbbjbg'\n"
b"Failed to register: Unable to acquire bus name 'launchpad.locallaunch.cacbahbebbbjbg'\n"
^CControl-C pressed. Exiting ...
```

**Comment by qstanczyk** [comment]
The "Control-C pressed. Exiting ..." comes from you pressing CTRL+C in the main console after Coordinator already crashed, right?

**Comment by Abinavraj5427** [comment]
Yes that is correct. After my coordinator finishes, pressing Ctrl+C terminates my actors and learners that are still running.

**Comment by qstanczyk** [comment]
I tried to repro your problem with examples/gym/lp_local_d4pg.py by adding max_actor_steps and with xterm console (export LAUNCHPAD_LAUNCH_LOCAL_TERMINAL=xterm). It works fine for me - once coordinator reaches the step limit launcher script terminates all nodes and exits cleanly.  When using 'current_terminal' replay and counter nodes have termination problems and they are hard-killed by the launch script after 10 seconds (need to investigate why that happens in this setup but not in case of xterm). But I can't reproduce your problem. Can you give the same example a try?

Repro steps:
```
[checkout acme to /tmp/acme]
docker run -e DISPLAY=$DISPLAY -it -v /tmp/.X11-unix:/tmp/.X11-unix:rw --rm --mount "type=bind,src=/tmp/acme,dst=/tmp/acme" -w /tmp/acme "python:3.8" bash
pip install --upgrade pip setuptools wheel
pip install -r requirements.txt
pip install .
cd examples/acme/gym
apt-get install xterm
export LAUNCHPAD_LAUNCH_LOCAL_TERMINAL=xterm
python3.8 lp_local_d4pg.py
```

**Comment by Abinavraj5427** [comment]
With the instructions given, I get the following problem for all nodes upon running `python3.8 lp_local_d4pg.py` without xterm:
```
[counter/0] Traceback (most recent call last):
[counter/0]   File "/usr/local/lib/python3.8/site-packages/launchpad/nodes/python/process_entry.py", line 90, in <module>
[counter/0]     app.run(main)
[counter/0]   File "/usr/local/lib/python3.8/site-packages/absl/app.py", line 303, in run
[counter/0]     _run_main(main, args)
[counter/0]   File "/usr/local/lib/python3.8/site-packages/absl/app.py", line 251, in _run_main
[counter/0]     sys.exit(main(argv))
[counter/0]   File "/usr/local/lib/python3.8/site-packages/launchpad/nodes/python/process_entry.py", line 74, in main
[counter/0]     functions = cloudpickle.load(open(FLAGS.data_file, 'rb'))
[counter/0] ModuleNotFoundError: No module named 'helpers'
```
Also when I try `apt-get install xterm`, I get a problem where it says `Package 'xterm' has no installation candidate` within the docker container, so I ran it without xterm to get the error above. Any ideas how to get around this to replicate?

**Comment by qstanczyk** [comment]
For the "No module named 'helpers'" issue, could you replace /usr/local/lib/python3.8/site-packages/launchpad/nodes/python/process_entry.py with https://github.com/deepmind/launchpad/blob/master/launchpad/nodes/python/process_entry.py. There was a fix to this problem which is not yet picked up by Acme's default build.

Did you do `apt-get update` to address the second problem?

**Comment by Abinavraj5427** [comment]
I was able to replicate the example on my 'current_terminal'. Like you mentioned, I was able to terminate all nodes except the replay and counter until the 10 second hard-kill. 

As for xterm, after running `apt-get update` and installing I was having a problem that looked like this regarding displays:
```
No protocol specified
Warning: This program is an suid-root program or is being run by the root user.
The full text of the error or warning message cannot be safely formatted
in this environment. You may get a more descriptive message by running the
program as a non-root user or by removing the suid bit on the executable.
xterm: Xt error: Can't open display: %s
```

Otherwise, the example seems to be working for killing the other nodes (except replay and counter) on time in `current_terminal`. I can try running my project in this environment temporarily.

**Comment by qstanczyk** [comment]
Perfect, glad that helped.
