### ISSUE TITLE
Launchpad compatible with ray tune?

### ISSUE THREAD

**Issue by wcarvalho** [deepmind/acme#183]
Great library. It's really useful and modular. I was considering running hyper-parameter searches with [ray tune](https://docs.ray.io/en/latest/tune/index.html). Is that compatible with launchpad?

Consider this atari R2D2 example: https://github.com/deepmind/acme/blob/c72b8284edd4e2c4738be6262e37d8a4b6fc0074/examples/atari/lp_r2d2_jax.py#L53

Right now, `lp.launch(program, lp.LaunchType.LOCAL_MULTI_PROCESSING)` seems to throw an error when I use `tune` saying that it needs to be in the main process. Do you know of a workaround?

**Comment by qstanczyk** [comment]
Does it throw a stack trace with some more details about the problem?

**Comment by wcarvalho** [comment]
Sorry! I should have attached this originally!

```
Function checkpointing is disabled. This may result in unexpected behavior when using checkpointing features or certain schedulers. To enable, set the train function arguments to be `func(config, checkpoint_dir=None)`.
2022-01-08 16:38:03,409	WARNING tune.py:570 -- Tune detects GPUs, but no trials are using GPUs. To enable trials to use GPUs, set tune.run(resources_per_trial={'gpu': 1}...) which allows Tune to expose 1 GPU to each trial. You can also override `Trainable.default_resource_request` if using the Trainable API.
(bundle_reservation_check_func pid=1913772) 2022-01-08 16:38:04.852338: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/home/wcarvalh/miniconda3/envs/acmejax/lib/
(bundle_reservation_check_func pid=1913772) RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
(ImplicitFunc pid=1913772) 2022-01-08 16:38:16,366	ERROR function_runner.py:268 -- Runner Thread raised error.
(ImplicitFunc pid=1913772) Traceback (most recent call last):
(ImplicitFunc pid=1913772)   File "/home/wcarvalh/miniconda3/envs/acmejax/lib/python3.9/site-packages/ray/tune/function_runner.py", line 262, in run
(ImplicitFunc pid=1913772)     self._entrypoint()
(ImplicitFunc pid=1913772)   File "/home/wcarvalh/miniconda3/envs/acmejax/lib/python3.9/site-packages/ray/tune/function_runner.py", line 330, in entrypoint
(ImplicitFunc pid=1913772)     return self._trainable_func(self.config, self._status_reporter,
(ImplicitFunc pid=1913772)   File "/home/wcarvalh/miniconda3/envs/acmejax/lib/python3.9/site-packages/ray/util/tracing/tracing_helper.py", line 451, in _resume_span
(ImplicitFunc pid=1913772)     return method(self, *_args, **_kwargs)
(ImplicitFunc pid=1913772)   File "/home/wcarvalh/miniconda3/envs/acmejax/lib/python3.9/site-packages/ray/tune/function_runner.py", line 597, in _trainable_func
(ImplicitFunc pid=1913772)     output = fn()
(ImplicitFunc pid=1913772)   File "/mnt/brain5/scratch/wcarvalh/projects/rljax/projects/msf/goto_distributed_search.py", line 26, in train_function
(ImplicitFunc pid=1913772)     train_goto(agent, num_actors, config_kwargs=config,
(ImplicitFunc pid=1913772)   File "/mnt/brain5/scratch/wcarvalh/projects/rljax/projects/msf/goto_distributed.py", line 102, in train
(ImplicitFunc pid=1913772)     lp.launch(program, lp.LaunchType.LOCAL_MULTI_PROCESSING)
(ImplicitFunc pid=1913772)   File "/home/wcarvalh/miniconda3/envs/acmejax/lib/python3.9/site-packages/launchpad/launch/launch.py", line 105, in launch
(ImplicitFunc pid=1913772)     return launch_local_multiprocessed.launch(program, local_resources,
(ImplicitFunc pid=1913772)   File "/home/wcarvalh/miniconda3/envs/acmejax/lib/python3.9/site-packages/launchpad/launch/local_multi_processing/launch.py", line 59, in launch
(ImplicitFunc pid=1913772)     return run_locally.run_commands_locally(commands, terminal)
(ImplicitFunc pid=1913772)   File "/home/wcarvalh/miniconda3/envs/acmejax/lib/python3.9/site-packages/launchpad/launch/run_locally/run_locally.py", line 146, in run_commands_locally
(ImplicitFunc pid=1913772)     return _LOCAL_LAUNCHER_MAP[_get_terminal(terminal)](commands)
(ImplicitFunc pid=1913772)   File "/home/wcarvalh/miniconda3/envs/acmejax/lib/python3.9/site-packages/launchpad/launch/run_locally/launch_local_tmux.py", line 43, in launch_with_tmux_session
(ImplicitFunc pid=1913772)     return _launch_with_multiplex_session(commands_to_launch,
(ImplicitFunc pid=1913772)   File "/home/wcarvalh/miniconda3/envs/acmejax/lib/python3.9/site-packages/launchpad/launch/run_locally/launch_local_tmux.py", line 154, in _launch_with_multiplex_session
(ImplicitFunc pid=1913772)     manager = worker_manager.WorkerManager()
(ImplicitFunc pid=1913772)   File "/home/wcarvalh/miniconda3/envs/acmejax/lib/python3.9/site-packages/launchpad/launch/worker_manager.py", line 148, in __init__
(ImplicitFunc pid=1913772)     self._sigterm_handler = register_signal_handler(signal.SIGTERM,
(ImplicitFunc pid=1913772)   File "/home/wcarvalh/miniconda3/envs/acmejax/lib/python3.9/site-packages/launchpad/launch/worker_manager.py", line 54, in register_signal_handler
(ImplicitFunc pid=1913772)     return signal.signal(sig, handler)
(ImplicitFunc pid=1913772)   File "/home/wcarvalh/miniconda3/envs/acmejax/lib/python3.9/signal.py", line 47, in signal
(ImplicitFunc pid=1913772)     handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
(ImplicitFunc pid=1913772) ValueError: signal only works in main thread of the main interpreter
(ImplicitFunc pid=1913772) Exception in thread Thread-2:
(ImplicitFunc pid=1913772) Traceback (most recent call last):
(ImplicitFunc pid=1913772)   File "/home/wcarvalh/miniconda3/envs/acmejax/lib/python3.9/threading.py", line 950, in _bootstrap_inner
(ImplicitFunc pid=1913772)     self.run()
(ImplicitFunc pid=1913772)   File "/home/wcarvalh/miniconda3/envs/acmejax/lib/python3.9/site-packages/ray/tune/function_runner.py", line 281, in run
(ImplicitFunc pid=1913772)     raise e
(ImplicitFunc pid=1913772)   File "/home/wcarvalh/miniconda3/envs/acmejax/lib/python3.9/site-packages/ray/tune/function_runner.py", line 262, in run
(ImplicitFunc pid=1913772)     self._entrypoint()
(ImplicitFunc pid=1913772)   File "/home/wcarvalh/miniconda3/envs/acmejax/lib/python3.9/site-packages/ray/tune/function_runner.py", line 330, in entrypoint
(ImplicitFunc pid=1913772)     return self._trainable_func(self.config, self._status_reporter,
(ImplicitFunc pid=1913772)   File "/home/wcarvalh/miniconda3/envs/acmejax/lib/python3.9/site-packages/ray/util/tracing/tracing_helper.py", line 451, in _resume_span
(ImplicitFunc pid=1913772)     return method(self, *_args, **_kwargs)
(ImplicitFunc pid=1913772)   File "/home/wcarvalh/miniconda3/envs/acmejax/lib/python3.9/site-packages/ray/tune/function_runner.py", line 597, in _trainable_func
(ImplicitFunc pid=1913772)     output = fn()
(ImplicitFunc pid=1913772)   File "/mnt/brain5/scratch/wcarvalh/projects/rljax/projects/msf/goto_distributed_search.py", line 26, in train_function
(ImplicitFunc pid=1913772)     train_goto(agent, num_actors, config_kwargs=config,
(ImplicitFunc pid=1913772)   File "/mnt/brain5/scratch/wcarvalh/projects/rljax/projects/msf/goto_distributed.py", line 102, in train
(ImplicitFunc pid=1913772)     lp.launch(program, lp.LaunchType.LOCAL_MULTI_PROCESSING)
(ImplicitFunc pid=1913772)   File "/home/wcarvalh/miniconda3/envs/acmejax/lib/python3.9/site-packages/launchpad/launch/launch.py", line 105, in launch
(ImplicitFunc pid=1913772)     return launch_local_multiprocessed.launch(program, local_resources,
(ImplicitFunc pid=1913772)   File "/home/wcarvalh/miniconda3/envs/acmejax/lib/python3.9/site-packages/launchpad/launch/local_multi_processing/launch.py", line 59, in launch
(ImplicitFunc pid=1913772)     return run_locally.run_commands_locally(commands, terminal)
(ImplicitFunc pid=1913772)   File "/home/wcarvalh/miniconda3/envs/acmejax/lib/python3.9/site-packages/launchpad/launch/run_locally/run_locally.py", line 146, in run_commands_locally
(ImplicitFunc pid=1913772)     return _LOCAL_LAUNCHER_MAP[_get_terminal(terminal)](commands)
(ImplicitFunc pid=1913772)   File "/home/wcarvalh/miniconda3/envs/acmejax/lib/python3.9/site-packages/launchpad/launch/run_locally/launch_local_tmux.py", line 43, in launch_with_tmux_session
(ImplicitFunc pid=1913772)     return _launch_with_multiplex_session(commands_to_launch,
(ImplicitFunc pid=1913772)   File "/home/wcarvalh/miniconda3/envs/acmejax/lib/python3.9/site-packages/launchpad/launch/run_locally/launch_local_tmux.py", line 154, in _launch_with_multiplex_session
(ImplicitFunc pid=1913772)     manager = worker_manager.WorkerManager()
(ImplicitFunc pid=1913772)   File "/home/wcarvalh/miniconda3/envs/acmejax/lib/python3.9/site-packages/launchpad/launch/worker_manager.py", line 148, in __init__
(ImplicitFunc pid=1913772)     self._sigterm_handler = register_signal_handler(signal.SIGTERM,
(ImplicitFunc pid=1913772)   File "/home/wcarvalh/miniconda3/envs/acmejax/lib/python3.9/site-packages/launchpad/launch/worker_manager.py", line 54, in register_signal_handler
(ImplicitFunc pid=1913772)     return signal.signal(sig, handler)
(ImplicitFunc pid=1913772)   File "/home/wcarvalh/miniconda3/envs/acmejax/lib/python3.9/signal.py", line 47, in signal
(ImplicitFunc pid=1913772)     handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
(ImplicitFunc pid=1913772) ValueError: signal only works in main thread of the main interpreter
2022-01-08 16:38:16,426	ERROR trial_runner.py:958 -- Trial train_function_423ec_00000: Error processing event.
Traceback (most recent call last):
  File "/home/wcarvalh/miniconda3/envs/acmejax/lib/python3.9/site-packages/ray/tune/trial_runner.py", line 924, in _process_trial
    results = self.trial_executor.fetch_result(trial)
  File "/home/wcarvalh/miniconda3/envs/acmejax/lib/python3.9/site-packages/ray/tune/ray_trial_executor.py", line 787, in fetch_result
    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)
  File "/home/wcarvalh/miniconda3/envs/acmejax/lib/python3.9/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/wcarvalh/miniconda3/envs/acmejax/lib/python3.9/site-packages/ray/worker.py", line 1713, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(TuneError): ray::ImplicitFunc.train_buffered() (pid=1913772, ip=141.212.113.244, repr=<types.ImplicitFunc object at 0x7f6c3f326e50>)
  File "/home/wcarvalh/miniconda3/envs/acmejax/lib/python3.9/site-packages/ray/tune/trainable.py", line 255, in train_buffered
    result = self.train()
  File "/home/wcarvalh/miniconda3/envs/acmejax/lib/python3.9/site-packages/ray/tune/trainable.py", line 314, in train
    result = self.step()
  File "/home/wcarvalh/miniconda3/envs/acmejax/lib/python3.9/site-packages/ray/tune/function_runner.py", line 381, in step
    self._report_thread_runner_error(block=True)
  File "/home/wcarvalh/miniconda3/envs/acmejax/lib/python3.9/site-packages/ray/tune/function_runner.py", line 531, in _report_thread_runner_error
    raise TuneError(
ray.tune.error.TuneError: Trial raised an exception. Traceback:
ray::ImplicitFunc.train_buffered() (pid=1913772, ip=141.212.113.244, repr=<types.ImplicitFunc object at 0x7f6c3f326e50>)
  File "/home/wcarvalh/miniconda3/envs/acmejax/lib/python3.9/site-packages/ray/tune/function_runner.py", line 262, in run
    self._entrypoint()
  File "/home/wcarvalh/miniconda3/envs/acmejax/lib/python3.9/site-packages/ray/tune/function_runner.py", line 330, in entrypoint
    return self._trainable_func(self.config, self._status_reporter,
  File "/home/wcarvalh/miniconda3/envs/acmejax/lib/python3.9/site-packages/ray/tune/function_runner.py", line 597, in _trainable_func
    output = fn()
  File "/mnt/brain5/scratch/wcarvalh/projects/rljax/projects/msf/goto_distributed_search.py", line 26, in train_function
    train_goto(agent, num_actors, config_kwargs=config,
  File "/mnt/brain5/scratch/wcarvalh/projects/rljax/projects/msf/goto_distributed.py", line 102, in train
    lp.launch(program, lp.LaunchType.LOCAL_MULTI_PROCESSING)
  File "/home/wcarvalh/miniconda3/envs/acmejax/lib/python3.9/site-packages/launchpad/launch/launch.py", line 105, in launch
    return launch_local_multiprocessed.launch(program, local_resources,
  File "/home/wcarvalh/miniconda3/envs/acmejax/lib/python3.9/site-packages/launchpad/launch/local_multi_processing/launch.py", line 59, in launch
    return run_locally.run_commands_locally(commands, terminal)
  File "/home/wcarvalh/miniconda3/envs/acmejax/lib/python3.9/site-packages/launchpad/launch/run_locally/run_locally.py", line 146, in run_commands_locally
    return _LOCAL_LAUNCHER_MAP[_get_terminal(terminal)](commands)
  File "/home/wcarvalh/miniconda3/envs/acmejax/lib/python3.9/site-packages/launchpad/launch/run_locally/launch_local_tmux.py", line 43, in launch_with_tmux_session
    return _launch_with_multiplex_session(commands_to_launch,
  File "/home/wcarvalh/miniconda3/envs/acmejax/lib/python3.9/site-packages/launchpad/launch/run_locally/launch_local_tmux.py", line 154, in _launch_with_multiplex_session
    manager = worker_manager.WorkerManager()
  File "/home/wcarvalh/miniconda3/envs/acmejax/lib/python3.9/site-packages/launchpad/launch/worker_manager.py", line 148, in __init__
    self._sigterm_handler = register_signal_handler(signal.SIGTERM,
  File "/home/wcarvalh/miniconda3/envs/acmejax/lib/python3.9/site-packages/launchpad/launch/worker_manager.py", line 54, in register_signal_handler
    return signal.signal(sig, handler)
  File "/home/wcarvalh/miniconda3/envs/acmejax/lib/python3.9/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread of the main interpreter
Traceback (most recent call last):
  File "/home/wcarvalh/miniconda3/envs/acmejax/lib/python3.9/site-packages/ipdb/__main__.py", line 305, in main
    pdb._runscript(mainpyfile)
  File "/home/wcarvalh/miniconda3/envs/acmejax/lib/python3.9/pdb.py", line 1573, in _runscript
    self.run(statement)
  File "/home/wcarvalh/miniconda3/envs/acmejax/lib/python3.9/bdb.py", line 580, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "/mnt/brain5/scratch/wcarvalh/projects/rljax/projects/msf/goto_distributed_search.py", line 1, in <module>
    from pathlib import Path
  File "/home/wcarvalh/miniconda3/envs/acmejax/lib/python3.9/site-packages/ray/tune/tune.py", line 718, in run_experiments
    return run(
  File "/home/wcarvalh/miniconda3/envs/acmejax/lib/python3.9/site-packages/ray/tune/tune.py", line 620, in run
    raise TuneError("Trials did not complete", incomplete_trials)
ray.tune.error.TuneError: ('Trials did not complete', [train_function_423ec_00000])


I'd like to point out the following error which seems to be raised by `launchpad/launch/run_locally/launch_local_tmux.py`:
```
ValueError: signal only works in main thread of the main interpreter
```

```

**Comment by qstanczyk** [comment]
Looks like Ray executes each search in a separate Thread, while Launchpad registers signal handlers, but it is not allowed to do from a non-main thread. Could you make Ray execute each search in a new process instead?

**Comment by wcarvalho** [comment]
This worked! Thank you. Here is a minimal example in case someone else finds this useful

```
import launchpad as lp
from ray import tune

mp.set_start_method('spawn') 

config_space = {
    "seed": tune.grid_search([1]),
    "agent": tune.grid_search(['some_agent'])
}


def create_and_run_program(config):
  """Create and run launchpad program
  """
  program = build_program(config)
  lp.launch(program, lp.LaunchType.LOCAL_MULTI_PROCESSING, terminal='current_terminal')



def train_function(config):
  """Runs inside a new thread and creates new process.
  """
  p = mp.Process(
    target=create_and_run_program, 
    args=(config,))
  p.start()
  p.join() # this blocks until the process terminates
  # this will call right away and end.



experiment_spec = tune.Experiment(
    name="experiment",
    run=train_function,
    config=config_space,
  )
all_trials = tune.run_experiments(experiment_spec)

```
