### ISSUE TITLE
Signal is not working

### ISSUE THREAD

**Issue by kovkev** [deepmind/acme#185]
I run `python3.9 examples/gym/lp_sac_jax.py` and get:

```
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
I1225 21:19:30.732187 140644471760704 xla_bridge.py:243] Unable to initialize backend 'tpu_driver': NOT_FOUND: Unable to find driver in registry given worker: 
I1225 21:19:30.732384 140644471760704 xla_bridge.py:243] Unable to initialize backend 'gpu': NOT_FOUND: Could not find registered platform with name: "cuda". Available platform names are: Host Interpreter
I1225 21:19:30.732703 140644471760704 xla_bridge.py:243] Unable to initialize backend 'tpu': INVALID_ARGUMENT: TpuPlatform is not available.
W1225 21:19:30.732816 140644471760704 xla_bridge.py:248] No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
[reverb/cc/platform/tfrecord_checkpointer.cc:150]  Initializing TFRecordCheckpointer in /tmp/tmpkxa6r6gu.
I1225 21:19:30.883024 140631112410880 courier_utils.py:51] Binding: run
I1225 21:19:30.884491 140631112410880 lp_utils.py:87] StepsLimiter: Starting with max_steps = 1000000 (actor_steps)
[reverb/cc/platform/tfrecord_checkpointer.cc:386] Loading latest checkpoint from /tmp/tmpkxa6r6gu
[reverb/cc/platform/default/server.cc:71] Started replay server on port 22255
I1225 21:19:30.888980 140629820557056 node.py:62] Reverb client connecting to: localhost:22255
I1225 21:19:32.412005 140624292452096 node.py:62] Reverb client connecting to: localhost:22255
I1225 21:19:32.412815 140605521848064 node.py:62] Reverb client connecting to: localhost:22255
I1225 21:19:32.418541 140630617470720 savers.py:166] Attempting to restore checkpoint: None
I1225 21:19:32.418889 140605488277248 node.py:62] Reverb client connecting to: localhost:22255
I1225 21:19:32.423120 140605479884544 node.py:62] Reverb client connecting to: localhost:22255
Error in atexit._run_exitfuncs: 10s.
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/launchpad/launch/worker_manager.py", line 408, in wait
    raise failure
  File "/usr/lib/python3.9/site-packages/launchpad/launch/worker_manager.py", line 454, in _check_workers
    worker.future.result()
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 438, in result
    return self.__get_result()
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
  File "/usr/lib/python3.9/site-packages/launchpad/launch/worker_manager.py", line 230, in run_inner
    future.set_result(f())
  File "/usr/lib/python3.9/site-packages/launchpad/nodes/python/node.py", line 75, in _construct_function
    return functools.partial(self._function, *args, **kwargs)()
  File "/usr/lib/python3.9/site-packages/launchpad/nodes/courier/node.py", line 107, in run
    instance = self._construct_instance()  # pytype:disable=wrong-arg-types
  File "/usr/lib/python3.9/site-packages/launchpad/nodes/python/node.py", line 177, in _construct_instance
    self._instance = self._constructor(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/acme/jax/layouts/distributed_layout.py", line 140, in counter
    return savers.CheckpointingRunner(
  File "/usr/lib/python3.9/site-packages/acme/tf/savers.py", line 211, in __init__
    signals.add_handler(signal.SIGTERM, _signal_handler)
  File "/usr/lib/python3.9/site-packages/acme/utils/signals.py", line 31, in add_handler
    signal.signal(signo.value, _wrapped)
  File "/usr/lib/python3.9/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread of the main interpreter
terminate called without an active exception
Fatal Python error: Aborted

Thread 0x00007fea57c76740 (most recent call first):
<no Python frame>
Aborted (core dumped)
```

**Comment by kovkev** [comment]
The same issue happens with `python3.7`

**Comment by kovkev** [comment]
Here is a colab reproducing this issue - https://colab.research.google.com/gist/kovkev/a47e34e1fab418189fbe7e04ccc861d0/acme.ipynb

**Comment by nikolamomchev** [comment]
Thanks for reporting. We have a fix and it will be available soon.

**Comment by qstanczyk** [comment]
Please give Acme v0.3.0 a try. Problem should be resolved there. Please reopen in case you still see some issues.
