### ISSUE TITLE
Basic SAC cartpole example fails: unexpected keyword argument 'minimum'

### ISSUE THREAD

**Issue by rdevon** [deepmind/acme#264]
Python 3.8.10, installing by cloning from GitHub and following the posted instructions, running the SAC example
`python run_sac.py --env_name gym:CartPole`

yields:

```
Traceback (most recent call last):
  File "run_sac.py", line 86, in <module>
    app.run(main)
  File "/usr/local/lib/python3.8/dist-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.8/dist-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "run_sac.py", line 73, in main
    config = build_experiment_config()
  File "run_sac.py", line 47, in build_experiment_config
    environment_spec = specs.make_environment_spec(environment)
  File "/usr/local/lib/python3.8/dist-packages/acme/specs.py", line 46, in make_environment_spec
    actions=environment.action_spec(),
  File "/usr/local/lib/python3.8/dist-packages/acme/wrappers/single_precision.py", line 42, in action_spec
    return _convert_spec(self._environment.action_spec())
  File "/usr/local/lib/python3.8/dist-packages/acme/wrappers/canonical_spec.py", line 54, in action_spec
    return _convert_spec(self._environment.action_spec())
  File "/usr/local/lib/python3.8/dist-packages/acme/wrappers/canonical_spec.py", line 68, in _convert_spec
    return tree.map_structure(_convert_single_spec, nested_spec)
  File "/usr/local/lib/python3.8/dist-packages/tree/__init__.py", line 430, in map_structure
    [func(*args) for args in zip(*map(flatten, structures))])
  File "/usr/local/lib/python3.8/dist-packages/tree/__init__.py", line 430, in <listcomp>
    [func(*args) for args in zip(*map(flatten, structures))])
  File "/usr/local/lib/python3.8/dist-packages/acme/wrappers/canonical_spec.py", line 63, in _convert_single_spec
    return spec.replace(
  File "/usr/local/lib/python3.8/dist-packages/dm_env/specs.py", line 146, in replace
    return type(self)(**all_kwargs)
TypeError: __init__() got an unexpected keyword argument 'minimum'
```

This might be related to a dependency, such as dm-tree, as this appears to happen on commit 71b2ab8577a118c103718f034fa62c5ad2c0fd97 (0.4.0) as well, which worked before.

**Comment by rdevon** [comment]
ah of course, because this is in the continuous examples

**Comment by Whojo** [comment]
It might still be worth to change this behavior, to prevent missleading information. Furthermore, this change is pretty inexpensive.
I must admit that I have lost a bit of time (as newcomer to RL) to figure out the problem before finding this closed issue.

The following change should do the work, from:
https://github.com/deepmind/acme/blob/d1e69c92000079b118b868ce9303ee6d39c4a0b6/acme/wrappers/canonical_spec.py#L62

To:
```python
 if type(spec) == specs.BoundedArray:
```

### Reminder of the problem
Using an environment which uses a `DiscreteArray` as action's spec (e.g. gym's `CartPole`) with the `CanonicalSpecWrapper` (which, to the best of my knowledge, should be used with continuous action space only) returns the above error, which is quite missleading.

### Expected behavior
Do not raise an error.
