### ISSUE TITLE
Changes in gym step and reset

### ISSUE THREAD

**Issue by rdevon** [deepmind/acme#266]
It looks like gym has recently changed their wrappers, such that they return an extra object:

On a fresh VM, cloning and installing acme, on `gym:Pendulum`
```
Traceback (most recent call last):
  File "run_sac.py", line 81, in <module>
    app.run(main)
  File "/usr/local/lib/python3.8/dist-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.8/dist-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "run_sac.py", line 74, in main
    experiments.run_experiment(
  File "/usr/local/lib/python3.8/dist-packages/acme/jax/experiments/run_experiment.py", line 170, in run_experiment
    eval_loop.run(num_episodes=num_eval_episodes)
  File "/usr/local/lib/python3.8/dist-packages/acme/environment_loop.py", line 179, in run
    result = self.run_episode()
  File "/usr/local/lib/python3.8/dist-packages/acme/environment_loop.py", line 106, in run_episode
    timestep = self._environment.step(action)
  File "/usr/local/lib/python3.8/dist-packages/acme/wrappers/single_precision.py", line 36, in step
    return self._convert_timestep(self._environment.step(action))
  File "/usr/local/lib/python3.8/dist-packages/acme/wrappers/canonical_spec.py", line 51, in step
    return self._environment.step(scaled_action)
  File "/usr/local/lib/python3.8/dist-packages/acme/wrappers/gym_wrapper.py", line 60, in step
    observation, reward, done, info = self._environment.step(action)
ValueError: too many values to unpack (expected 4)
[reverb/cc/platform/default/server.cc:84] Shutting down replay server
```

Adding a placeholder for that extra value doesn't seem to help though, as it seems like the replay buffer hangs.

These changes probably happened earlier in one of their commits, but they recently pushed to pypi, so anyone installing using the setup.py here will encounter this issue.

**Comment by sinopalnikov** [comment]
should be fixed with https://github.com/deepmind/acme/commit/29dc09431cdbf9002a8ed7ef1d47fbcdc9308252

**Comment by rdevon** [comment]
Sounds good. Downgrading gym worked for me.
