### ISSUE TITLE
ImportError: libpython3.7m.so.1.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by drozzy** [deepmind/acme#65]
I don't know what's happening. I'm trying to run the example quickstart, and I get an error.
```
2020-08-29 02:33:26.072561: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
Traceback (most recent call last):
  File "quickstart.py", line 3, in <module>
    from acme.adders import reverb as adders
  File "/home/user/anaconda3/envs/myproj/lib/python3.7/site-packages/acme/adders/reverb/__init__.py", line 21, in <module>
    from acme.adders.reverb.base import DEFAULT_PRIORITY_TABLE
  File "/home/user/anaconda3/envs/myproj/lib/python3.7/site-packages/acme/adders/reverb/base.py", line 26, in <module>
    import reverb
  File "/home/user/anaconda3/envs/myproj/lib/python3.7/site-packages/reverb/__init__.py", line 27, in <module>
    from reverb import item_selectors as selectors
  File "/home/user/anaconda3/envs/myproj/lib/python3.7/site-packages/reverb/item_selectors.py", line 19, in <module>
    from reverb import pybind
  File "/home/user/anaconda3/envs/myproj/lib/python3.7/site-packages/reverb/pybind.py", line 1, in <module>
    import tensorflow as _tf; from .libpybind import *; del _tf
ImportError: libpython3.7m.so.1.0: cannot open shared object file: No such file or directory
```

Here is my complete enviornment (conda) file that I create:
```
name: myenv
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.7
  - jupyterlab
  - pytorch
  - torchvision 
  - cudatoolkit=10.1
  - pip
  - pip:    
    - reverb
    - tensorflow==2.3
    - dm-reverb-nightly #             (reberb)
    - tensorflow-probability # missing
    - wrapt # missing 
    - dm-sonnet # missing
    - graphs # missing
    - trfl # missing 
    - dm-acme
    - dm-acme[reverb]
    - dm-acme[tf]    
    - dm-acme[envs]
    # for visualizing
    - ffmpeg
    - gym
    - imageio
    - PILLOW 
    - pyglet
    - pyvirtualdisplay
    - imageio-ffmpeg
```

and here is my python file:
```
from acme import environment_loop
from acme.tf import networks
from acme.adders import reverb as adders
from acme.agents.tf import actors as actors
from acme.datasets import reverb as datasets
from acme.wrappers import gym_wrapper
from acme import specs
from acme import wrappers
from acme.agents.tf import d4pg
from acme.agents import agent
from acme.tf import utils as tf2_utils
from acme.utils import loggers

import gym
import dm_env
import numpy as np
import reverb
import sonnet as snt
import tensorflow as tf

# Import dm_control if it exists.
try:
    from dm_control import suite
except (OSError, ModuleNotFoundError):
    pass

def main():
    environment, environment_spec = load_environment()

    agent = create_agent(environment_spec)

    run_training_loop(environment, agent)

def load_environment():
    environment = gym_wrapper.GymWrapper(gym.make('MountainCarContinuous-v0'))
    environment = wrappers.SinglePrecisionWrapper(environment)

    def render(env):
        return env.environment.render(mode='rgb_array')

    # Grab the spec of the environment.
    environment_spec = specs.make_environment_spec(environment)
    return environment, environment_spec

def create_agent(environment_spec):
    #@title Build agent networks

    # Get total number of action dimensions from action spec.
    num_dimensions = np.prod(environment_spec.actions.shape, dtype=int)

    # Create the shared observation network; here simply a state-less operation.
    observation_network = tf2_utils.batch_concat

    # Create the deterministic policy network.
    policy_network = snt.Sequential([
        networks.LayerNormMLP((256, 256, 256), activate_final=True),
        networks.NearZeroInitializedLinear(num_dimensions),
        networks.TanhToSpec(environment_spec.actions),
    ])

    # Create the distributional critic network.
    critic_network = snt.Sequential([
        # The multiplexer concatenates the observations/actions.
        networks.CriticMultiplexer(),
        networks.LayerNormMLP((512, 512, 256), activate_final=True),
        networks.DiscreteValuedHead(vmin=-150., vmax=150., num_atoms=51),
    ])

    # 3. Create a logger for agent specific diagnostics.
    agent_logger = loggers.TerminalLogger(label='agent', time_delta=10)

    # Create the D4PG agent.
    agent = d4pg.D4PG(
        environment_spec=environment_spec,
        policy_network=policy_network,
        critic_network=critic_network,
        observation_network=observation_network,
        logger=agent_logger,
        checkpoint=False
    )
    return agent

def run_training_loop(environment, agent):
    # Create a logger for agent specific diagnostics.
    env_loop_logger = loggers.TerminalLogger(label='env_loop', time_delta=10)

    env_loop = environment_loop.EnvironmentLoop(environment, agent, logger=env_loop_logger)
    env_loop.run(num_episodes=100)
```

**Comment by drozzy** [comment]
Perhaps reberb/tensorflow version is wrong? But tf 2.3 is out and it should work... I also downgraded cuda to 10.1 from 10.2.

**Comment by AthinkingNeal** [comment]
Maybe you can try `sudo apt-get install libpython3.7`, it solves my problem when running in a virtual environment,
also, you can refer to this issue #47

**Comment by fastturtle** [comment]
Hi @drozzy, what OS are you using? Reverb currently only supports Linux OSes.

**Comment by drozzy** [comment]
I think it was linux. Sorry, I don't use this anymore, so I'll close this issue and if someone has a similar problem they can re-file.
