### ISSUE TITLE
run_dqfd.py error

### ISSUE THREAD

**Issue by yiwc** [deepmind/acme#66]
Dear acme team,

An assertion error got, when running "run_dqfd.py". Any idea about this?
Thank you!

Traceback (most recent call last):
  File "/home/yiwen/pjs/v3/ws/acme/examples/bsuite/run_dqfd.py", line 83, in <module>
    app.run(main)
  File "/home/yiwen/anaconda3/envs/acme/lib/python3.6/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/home/yiwen/anaconda3/envs/acme/lib/python3.6/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/home/yiwen/pjs/v3/ws/acme/examples/bsuite/run_dqfd.py", line 72, in main
    demonstration_dataset=bsuite_demonstrations.make_dataset(raw_environment),
  File "/home/yiwen/anaconda3/envs/acme/lib/python3.6/site-packages/acme/agents/tf/dqfd/bsuite_demonstrations.py", line 132, in make_dataset
    assert isinstance(environment, deep_sea.DeepSea)
KeyboardInterrupt

**Comment by E666GT** [comment]
Thanks, fixed by this
run_dqfd.py line:72
`demonstration_dataset=bsuite_demonstrations.make_dataset(raw_environment),`
to
`demonstration_dataset=bsuite_demonstrations.make_dataset(raw_environment.raw_env),`
