### ISSUE TITLE
"TypeError: can't pickle _thread.RLock objects" when attempting to load saved agent

### ISSUE THREAD

**Issue by sdkramer10** [deepmind/acme#89]
Hi,

I wrote the following code to save my agent:

```
  agent = dqn.DQN(environment_spec=environment_spec, network=network)
  loop = acme.EnvironmentLoop(environment, agent)
  loop.run(num_episodes=10)
  agent._learner._snapshotter.save()
```

I then later try to load this saved agent:

```
learner = tf.saved_model.load("./savedModelDir/")
environment = wrappers.SinglePrecisionWrapper(AmplitudeEnvironment())
environment_spec = specs.make_environment_spec(environment)
agent = dqn.DQN(environment_spec, learner)
```

Which results in the following error

Traceback (most recent call last):
  File "./agent_inference.py", line 33, in <module>
    main()
  File "./agent_inference.py", line 16, in main
    agent = dqn.DQN(environment_spec, learner)
  File "/usr/local/lib/python3.7/site-packages/acme/agents/tf/dqn/agent.py", line 127, in __init__
    target_network = copy.deepcopy(network)
  File "/usr/local/lib/python3.7/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/local/lib/python3.7/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/local/lib/python3.7/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/local/lib/python3.7/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/local/lib/python3.7/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/local/lib/python3.7/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/local/lib/python3.7/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/local/lib/python3.7/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/local/lib/python3.7/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/local/lib/python3.7/copy.py", line 215, in _deepcopy_list
    append(deepcopy(a, memo))
  File "/usr/local/lib/python3.7/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/local/lib/python3.7/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/local/lib/python3.7/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/local/lib/python3.7/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/local/lib/python3.7/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/local/lib/python3.7/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/local/lib/python3.7/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/local/lib/python3.7/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/local/lib/python3.7/copy.py", line 169, in deepcopy
    rv = reductor(4)
TypeError: can't pickle _thread.RLock objects

It seems like the network saved by the dqn learner is not able to be deep copied when loaded back in by the agent. Any suggestions? Thanks!

**Comment by fastturtle** [comment]
Hi @sdkramer10, there aren't any RLock objects in the Acme codebase. Have
you introduced any yourself?

**Comment by sdkramer10** [comment]
Hey @fastturtle! Thanks for the quick reply. I started using the deepmind libraries this week, and it's been a great way to learn RF.

 No, I have not introduced any Rlock objects. This thread (https://github.com/tensorflow/tensorflow/issues/11157#issuecomment-470418990) makes it seem like the error happens when you have a lambda layer in the network, so I'm guessing that under the hood DQN is using one? In the meantime, I'm going to follow the suggestion of saving weigths alone and using a constructor function to build the model itself.

**Comment by fastturtle** [comment]
Yeah it looks like a lambda is being saved, have you been able to track it down?

**Comment by sdkramer10** [comment]
I was not able to track down the lambda, but I did find a suitable workaround by using the TF checkpoint feature and then manually reconstructing the model. 

To save the agent:

```
network = snt.Sequential([
  snt.Flatten(),
  snt.nets.MLP([50, 50, 5])
])
checkpoint = tf.train.Checkpoint(module=network)
agent = dqn.DQN(environment_spec=environment_spec, network=network, checkpoint=False)
loop = acme.EnvironmentLoop(environment, agent)
loop.run(num_episodes=100)
checkpoint.save(path)
```
And then to load the agent back in:

```

network = snt.Sequential([
  snt.Flatten(),
  snt.nets.MLP([50, 50, 5])
])
checkpoint = tf.train.Checkpoint(module=network)
latest = tf.train.latest_checkpoint(path)
checkpoint.restore(latest)
agent = dqn.DQN(environment_spec=environment_spec, network=network, checkpoint=False)
```
